// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb && kDebugMode) return webDev;
    if (kIsWeb) return webPrd;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webPrd = FirebaseOptions(
    apiKey: 'AIzaSyANMk8iUo9WebanWeLmw2XIKyZrcA51A-k',
    authDomain: 'forgotten-land.firebaseapp.com',
    projectId: 'forgotten-land',
    storageBucket: 'forgotten-land.appspot.com',
    messagingSenderId: '105370210991',
    appId: '1:105370210991:web:67d908bdc67265e26cba5a',
    measurementId: 'G-H81S7PDXY8',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyDxdLhWgmeOOZ0kalFctHyVxZGB0iit2Us',
    authDomain: 'forgotten-land-dev.firebaseapp.com',
    projectId: 'forgotten-land-dev',
    storageBucket: 'forgotten-land-dev.appspot.com',
    messagingSenderId: '637077426189',
    appId: '1:637077426189:web:9e9aa6e5c0b576f42b8544',
    measurementId: 'G-9X4JVECNXW',
  );
}
